# shell colors
export CLICOLOR=1
export LS_COLORS='di=94:fi=0:ln=31:pi=5:so=5:bd=5:cd=5:or=31:mi=0:ex=35:*.rpm=90'

# less should be able to read zipped files
export LESSOPEN="|~/shared/bin/lesspipe.sh %s"

# exports for third party tools

# exports for development

# aliases to log into various machines

# alias to mount/unmount directories from other machines

# aliases for commands
alias ll='ls -alh'
alias search='grep -rHn -e'
alias rsync='rsync -aHxv --numeric-ids --progress -e "ssh -T -c arcfour -o Compression=no -x"'

# some useful commands
mkpw () {
    openssl rand -base64 48
}

# export path updates
export PATH=~/bin:/usr/local/bin:/usr/local/sbin:${PATH}
